language: rust

sudo: required

rust:
  - nightly

cache: cargo

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"

script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
